require("core.plugins")
require("core.config")
require("core.autocmds")

-- high priority for langmapper plugin
require("plugins.text-objects")
require("plugins.langmapper")
-- end

require("core.mappings")

require("plugins.theme")
require("plugins.neo-tree")
require("plugins.treesitter")
require("plugins.lsp")
require("plugins.typescript-tools")
require("plugins.mason")
require("plugins.pairs")
require("plugins.autotag")
require("plugins.comment")
require("plugins.gitsigns")
require("plugins.smart-splits")
require("plugins.jest")
require("plugins.quicknote")
require("plugins.surround")
require("plugins.treesitter-textobjects")
require("plugins.neocodeium")
require("plugins.arrow")
require("plugins.logsitter")
require("plugins.fzf-lua")
require("plugins.codecompanion")
require("plugins.blink-cmp")
require("plugins.obsidian-nvim")
require("plugins.conform")
require("plugins.indent")
